<?php

/**
 * BaseContestant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $speed_factor
 * 
 * @method string     getName()         Returns the current record's "name" value
 * @method string     getSpeedFactor()  Returns the current record's "speed_factor" value
 * @method Contestant setName()         Sets the current record's "name" value
 * @method Contestant setSpeedFactor()  Sets the current record's "speed_factor" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContestant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contestant');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('speed_factor', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}